-- FIELDBYTE EDGE | DATABASE SCHEMA
-- Target: PUMP-001 Telemetry

CREATE TABLE sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    serial_number TEXT NOT NULL,
    vibration_de_x_rms REAL,
    bearing_temp_de REAL,
    rpm INTEGER,
    suction_pressure REAL,
    discharge_pressure REAL,
    
    -- The Autonomous Edge Calculation (Saves Hardware CPU Cycles)
    differential_pressure REAL GENERATED ALWAYS AS (discharge_pressure - suction_pressure) STORED,
    
    overall_status INTEGER DEFAULT 0
);

-- Note for future devs: 
-- To implement the 30-day rolling data retention, enable the pg_cron extension
-- and schedule a DELETE job for rows where recorded_at < NOW() - INTERVAL '30 days'.